application: electricsheep-1
version: 1
runtime: python
api_version: 1

# http://code.google.com/appengine/docs/python/config/appconfig.html

default_expiration: 0

derived_file_type:
  - python_precompiled

# error_handlers:
#   - file: error.html

builtins:
# - admin_redirect: on  # @ /_ah/admin ...  redirects local dev console to admin console dashboard
# - appstats: on        # @ /_ah/stats/
# - remote_api: on      # @ /_ah/remote_api
- datastore_admin: on # @ /_ah/datastore_admin/

admin_console:
  pages:
    - name: Appstats
      url: /console/stats
    - name: CGI Request Info
      url: /console/cgi-info

handlers:

  - url: /console/admin.*
    script: $PYTHON_LIB/google/appengine/ext/admin
    login: admin
    # see http://code.google.com/appengine/docs/python/config/appconfig.html#Referring_to_the_Python_Library_Directory

  - url: /console/stats.*
    script: $PYTHON_LIB/google/appengine/ext/appstats/ui.py
    # see http://code.google.com/appengine/docs/python/tools/appstats.html#Setting_Up_the_Administrative_Interface
    # you can also set this to default url via builtins/remote_api since sdk 1.3.8

  - url: /console/cgi-info.*
    script: app/cgi_info.py
    # see the script for configuration

  - url: /console/static
    static_dir: app/console/app/view/static
    # see http://con.appspot.com/console/help/integration

  - url: /console.*
    script: app/console/app/console.py
    # see http://con.appspot.com/console/help/integration


  - url: /img
    static_dir: img

  - url: /css
    static_dir: css

  - url: /js
    static_dir: js

  - url: /static
    static_dir: static

  - url: /favicon.ico
    upload: etc/favicon.ico
    static_files: etc/favicon.ico
    mime_type: image/x-icon
    expiration: 8h
    # size 16x16 or 32x32
    # - https://secure.wikimedia.org/wikipedia/en/wiki/Favicon

  - url: /robots.txt
    upload: etc/robots.txt
    static_files: etc/robots.txt
    expiration: 8h

  - url: /.*
    script: main.py
